### ISSUE TITLE
Tickets are live announcement

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd22-tasks#10]

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/194746893-65d37184-b7d8-4579-abd6-f776b6951943.png)

**Comment by kalyan678** [comment]
@inovizz  @Amritha-Madam  Post is scheduled and it will be out tomorrow at 9 am.

**Comment by kalyan678** [comment]
This post was published successfully. We can now close this task. Thank you!
