### ISSUE TITLE
CFP Reminder

### ISSUE THREAD

**Issue by Amritha-Madam** [HydPy/pyconfhyd22-tasks#11]

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/198861968-8d1f2d13-9dea-4ec1-a9e3-4b7697e5acca.png)

**Comment by Subuhani93** [comment]
![Pycon CFP Flyers-01](https://user-images.githubusercontent.com/116994436/198863971-78450a01-eab6-46da-ab28-c7ae88e82572.jpg)
