### ISSUE TITLE
Be like Bill Campaign

### ISSUE THREAD

**Issue by Amritha-Madam** [HydPy/pyconfhyd22-tasks#13]

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/198861952-81a0bf64-4ad2-451c-975f-1c7d0bd1bbbd.png)

**Comment by Subuhani93** [comment]
![Pycon CFP Flyers-06](https://user-images.githubusercontent.com/116994436/198863895-55e41eea-3737-4c3c-b182-112b26f57af4.jpg)
