### ISSUE TITLE
Workshop CFP open

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd22-tasks#14]

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/198861994-e3464e81-c0ba-4f54-b6b2-5ef15efad960.png)

**Comment by Subuhani93** [comment]
![Pycon CFP Flyers-03](https://user-images.githubusercontent.com/116994436/198863873-f2cdb31d-5903-4461-8c2e-f4c69e8294b7.jpg)
