### ISSUE TITLE
Announce Sponsors

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd22-tasks#16]

**Comment by inovizz** [comment]
![1](https://user-images.githubusercontent.com/3849885/202351581-4e51b80a-3edc-4118-bd62-fd8ff07a1e2e.png)
![2](https://user-images.githubusercontent.com/3849885/202351603-a10f995f-f036-4ad3-b576-fc25f295e070.png)
![3](https://user-images.githubusercontent.com/3849885/202351607-62b42b6c-ea03-4b97-94c4-6d2768e29745.png)
![4](https://user-images.githubusercontent.com/3849885/202351611-ad262bbf-dd42-439f-a9ee-345432ca6d8f.png)
![5](https://user-images.githubusercontent.com/3849885/202351612-80c72948-2ef7-4fd1-a94e-2e2c6040a06d.png)
![6](https://user-images.githubusercontent.com/3849885/202351615-87289352-42f4-42ca-b112-72817d98f6b3.png)

**Comment by inovizz** [comment]
![PyConfFlyers(7)](https://user-images.githubusercontent.com/3849885/204205347-f454cf66-c5a9-4b48-905a-9ce5692e11d6.png)

**Comment by kalyan678** [comment]
@inovizz    Thanks for your help! We can close this issue.

**Comment by inovizz** [comment]
![8](https://user-images.githubusercontent.com/3849885/205823298-9ff4cd71-6450-49d3-bac4-6f408cb2e046.png)
![9](https://user-images.githubusercontent.com/3849885/205823323-94bd12ab-e96c-49ee-b079-4ef9d916983e.png)

**Comment by kalyan678** [comment]
@inovizz   Thanks for your support. We are good to close this issue :)
