### ISSUE TITLE
Announce Speakers on SM

### ISSUE THREAD

**Issue by snehithallamraju** [HydPy/pyconfhyd22-tasks#18]

**Comment by snehithallamraju** [comment]
Workshop Speakers

Aniket Maurya : [@aniketmaurya](http://twitter.com/aniketmaurya)
Jayesh Sharma : [@wjayesh](http://twitter.com/wjayesh)

![workshop2](https://user-images.githubusercontent.com/20667307/204722292-7dab3f27-9b9c-489a-b1c8-1f921c11a39b.png)

**Comment by snehithallamraju** [comment]
Workshop Speakers
Satyam Soni : [@satyam_soni1306](http://twitter.com/satyam_soni1306)
Sasidhar Donaparthi : [@sdonapar](http://twitter.com/sdonapar)
![workshop2](https://user-images.githubusercontent.com/20667307/204736177-32c89d14-a31f-44d2-bbcf-43238a213e68.png)

**Comment by snehithallamraju** [comment]
Lightning Talk Speakers :

Kaushal : [@kau5hal10](http://twitter.com/kau5hal10)
Ashok Tankala : [@ashok_tankala](http://twitter.com/ashok_tankala)
Hemangi Karchalkar : NA

![lightning talk](https://user-images.githubusercontent.com/20667307/204739258-167e82bb-50a9-458c-b00a-b0827ef69de8.png)

**Comment by snehithallamraju** [comment]
General Talks Speakers

Jatin Goel : [@_JatinGoel](http://twitter.com/_JatinGoel)
Kesia Mary Joies : https://www.linkedin.com/in/kesiajoies/
Abhinand C : https://www.linkedin.com/in/abhinand-c/
Abdeali Kothari : [@AbdealiJK](http://twitter.com/AbdealiJK)
Sharmistha Chatterjee : [@sharmichat_82](http://twitter.com/sharmichat_82)
Nabarun Pal : [@theonlynabarun](http://twitter.com/theonlynabarun)


![Talks1](https://user-images.githubusercontent.com/20667307/205006774-c56da989-a5dc-4929-8ed3-f24192724e12.png)
![Talks2](https://user-images.githubusercontent.com/20667307/205006785-3990756e-ad1d-4ba3-a02e-ecaa01ce5b31.png)
![Talks3](https://user-images.githubusercontent.com/20667307/205006791-30c32961-eea3-4db3-9896-a5c5d3252abf.png)

**Comment by kalyan678** [comment]
@snehithallamraju  @inovizz 
Thanks for your help. We are good to close this task.
