### ISSUE TITLE
PyConf Logo 

### ISSUE THREAD

**Issue by bhansa** [HydPy/pyconfhyd22-tasks#2]
![pyconf_logo](https://user-images.githubusercontent.com/9723884/191257330-0c411e35-6848-4edf-a661-70a3b4f53ae8.svg)
![python logo](https://user-images.githubusercontent.com/9723884/191257570-cdc54c3a-4231-455a-a3e1-0b202d2a516b.svg)

**Comment by inovizz** [comment]
Hi @bhansa - can you share the PNG file with me on transparent background? I'd ask @kalyan678 to change the logo on all SM channels.

**Comment by bhansa** [comment]
Added PNG's 

![pyconf_logo](https://user-images.githubusercontent.com/9723884/191455158-12e2df78-57e2-4a23-878b-e25b0127dbba.png)
![python logo](https://user-images.githubusercontent.com/9723884/191455176-ead2cc3f-f26f-49d0-96ba-fce1c82ecd66.png)

**Comment by ananyo2012** [comment]
![Pyconf 2022-01](https://user-images.githubusercontent.com/10486343/194361947-8adc9511-7823-454c-a38b-3cb178e5827c.png)
