### ISSUE TITLE
Sponsorship is Open announcement to be done

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd22-tasks#6]
Next week (starting 10th Oct)

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/194746883-22a9dca4-0b65-4996-ae11-0f936a25e195.png)

**Comment by inovizz** [comment]
![PyConfFlyers(5)](https://user-images.githubusercontent.com/3849885/194747505-c2ba7ee3-6b3d-4571-a395-f839dd32f553.png)

**Comment by kalyan678** [comment]
@inovizz  Post will be live on 12th Oct , 9:00 AM.
@Amritha-Madam  Once it is live on Twitter & Linkedin. You can post the same on Instagram. Thanks in advance for your help!!
