### ISSUE TITLE
Venue announcement post 

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd22-tasks#7]
Next week (starting 10th Oct)

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/198862013-43146a05-0e05-481f-a3d0-96835e4fd0c0.png)
![image](https://user-images.githubusercontent.com/3849885/198862021-5e343a34-cf21-47ce-9d6b-962b368db0aa.png)

**Comment by Subuhani93** [comment]
![Pycon CFP Flyers-03](https://user-images.githubusercontent.com/116994436/198863909-44b72149-8b08-4c8f-a55f-139c4f064911.jpg)
![Pycon CFP Flyers-02](https://user-images.githubusercontent.com/116994436/198863913-74318399-11d6-4aa4-af4f-e0d6431a559e.jpg)
