### ISSUE TITLE
Call for Community Partners

### ISSUE THREAD

**Issue by sanghisha145** [HydPy/pyconfhyd22-tasks#9]
Pyconf Hyderabad 2022

Expected date - 8th Oct 11:00 am

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/198862037-bed7ec26-2594-46f4-b6d4-032b59d5e722.png)

**Comment by Subuhani93** [comment]
![Pycon CFP Flyers-05](https://user-images.githubusercontent.com/116994436/198863903-5cc68268-43d4-4c67-b24f-99f3c1aaf0e6.jpg)
